revert: "chore: update compose to v1.12.0"
java.lang.NoSuchMethodError: 'org.jetbrains.skia.Data org.jetbrains.skia.Image.encodeToData$default(org.jetbrains.skia.Image, org.jetbrains.skia.EncodedImageFormat, int, int, java.lang.Object)'

Waiting for filekit and nucleus upgrade

This reverts commit 1598d67ebd85b823adc82e566c9df890823c4528.